#!/bin/bash

[[ "$TRACE" ]] && set -x

function error_exit {
	echo "${1:-"Unknown Error"}" 1>&2
	exit 1
}

#Use ENV vars for paths
LOCAL=${VOLUME_PATH}
REMOTE=${S3_PATH}

if [ -z ${LOCAL} ] || [ -z ${REMOTE} ]; then
    echo "You must provide a local and remote path"
    exit 1
fi

function restore {
  if [ "$(ls -A $LOCAL)" ]; then
		if [[ ${FORCE_RESTORE:false} == 'true' ]]; then
    	error_exit "local directory is not empty"
		fi
  fi

  echo "restoring $REMOTE => $LOCAL"
  if ! aws s3 sync "$REMOTE" "$LOCAL"; then
    error_exit "restore failed"
  fi
}

function backup {
  echo "backup $LOCAL => $REMOTE"
  if ! aws s3 sync "$LOCAL" "$REMOTE"; then
    echo "backup failed" 1>&2
    return 1
  fi
}

function final_backup {
  echo "backup $LOCAL => $REMOTE"
  while ! aws s3 sync "$LOCAL" "$REMOTE"; do
    echo "backup failed" 1>&2
    sleep 1
  done
  exit 0
}

function idle {
  echo "ready"
  while true; do
    sleep 42 &
    wait $!
  done
}

restore

trap final_backup SIGHUP SIGINT SIGTERM
trap "backup; idle" USR1

idle
